apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: >-
    Host={{ .Values.postgres.host }};
    Port={{ .Values.postgres.port }};
    Database={{ .Values.postgres.database }};
    Username={{ .Values.postgres.username }};
    Password={{ .Values.postgres.password }}