replicaCount: 1
 
image:
  repository: nestorperez007/bootcampclt-api
  tag: "1.1"
  pullPolicy: Always
 
app:
  containerPort: 8080
  env:
    aspnetcoreEnvironment: Development
 
service:
  type: NodePort
  port: 80
  targetPort: 8080

serilog:
  group: "productos"
  ApplicationName: api-bootcamp-clt

seq:
  serverUrl: "http://seq.infra"
  group: "productos"
 
env:
  percentDiscount: "30"
  categoriesDiscount: "4"

postgres:
  host: postgres-svc
  port: 5432
  database: hardwareCLT
  username: postgres
  password: "a.123456"   # Para demo local. En equipos reales, no commitear.